### ISSUE TITLE
misc

### ISSUE THREAD

**Issue by boneyard93501** [fluencelabs/aqua-dht#20]
* unstable try trait, , https://github.com/fluencelabs/aqua-dht/blob/2a7f5cec193073aad5982b903b4b1ff3d543b834/src/main.rs#L1 throws an error

```rust
bp16~/localdev/aqua-dht(bb|✚4…) % ./build.sh
    Updating crates.io index
   Compiling aqua-dht v0.1.0 (/Users/bebo/localdev/aqua-dht)
error[E0635]: unknown feature `try_trait`
 --> src/main.rs:1:12
  |
1 | #![feature(try_trait)]
  |            ^^^^^^^^^
```

* this `Note: all timestamps should be passed as result of ("op" "timestamp_sec") builtin call.` to me is problematic since it prevents use of `mrepl`.  maybe `check_timestamp_tetraplets ` can be made faggble.

* https://github.com/fluencelabs/aqua-dht#register_keykey-string-current_timestamp-u64-weight-u32 : signature is missing `pin: bool`

* deployment to network didn't work for me (as it never does with larger file uploads):
```bash
 % ./deploy.sh
Something went wrong!
Timed out after 60000ms
12D3KooWFRgVmb1uWcmCbmJqLr8tBQghL6ysSpK2VyE2VZbaQ6wy deployed
client seed: 4VzczoMt73wVenKyJhZ6MySsT8jCy1MXKC6kD8vvgDoK
client peerId: 12D3KooWFRgVmb1uWcmCbmJqLr8tBQghL6ysSpK2VyE2VZbaQ6wy
relay peerId: 12D3KooWSD5PToNiLQwKDXsu8JSysCwUt8BVUJEqCHcDe7P5h45e
[
  "{\"error\":\"Local service error: ret_code is 1, error message is '\\\"Error: Service with id '12D3KooWFRgVmb1uWcmCbmJqLr8tBQghL6ysSpK2VyE2VZbaQ6wy' not found\\\"'\",\"instruction\":\"call relay (\\\"srv\\\" \\\"add_alias\\\") [alias service] result\"}"
]
Particle timed out, exiting
```

**Comment by justprosh** [comment]
divided into #26 #27 #28 and issue with `try_trait` had already resolved
