### ISSUE TITLE
fstrings = sql injection

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua-dht#34]
please use parameters or parse-validate clean inputs

**Comment by folex** [comment]
@dzmitry-lahoda can you please be more clear on the issue? What is `fstring`? What API methods are affected? How to reproduce SQL Injection?

**Comment by dzmitry-lahoda** [comment]
all api methods which do not validate input neither use sql parameters are subject to sql injections as per wikipedia article.

**Comment by dzmitry-lahoda** [comment]
```
INSERT OR REPLACE INTO {VALUES_TABLE_NAME} \
                    VALUES ('{key}', '{value}', '{peer_id}', '{set_by}', '{relay_id}',\
                    '{service_id}', '{current_timestamp_sec}', '{current_timestamp_sec}', '{weight}')"
```

if `value` something like
```
value', 'a','b', .. ) ; DELETE FROM ... ;
```

**Comment by dzmitry-lahoda** [comment]
```
INSERT OR REPLACE INTO {VALUES_TABLE_NAME} \
                    VALUES ('{key}', '{value}', '{peer_id}', '{set_by}', '{relay_id}',\
                    '{service_id}', '{current_timestamp_sec}', '{current_timestamp_sec}', '{weight}')"
```

if `value` something like
```
value', 'a','b', .. );  DELETE FROM ... ; INSERT OR REPLACE INTO {VALUES_TABLE_NAME} VALUES ('{key}','a
```

**Comment by justprosh** [comment]
Nope, value is passed in single quotes and can't be treated as SQL expression

**Comment by justprosh** [comment]
Maybe we should restrict to use of single quotes in strings and SQL injection will be impossible because the value is passed in single quotes
