### ISSUE TITLE
redistribute wasm along with aqua scripts

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua-dht#42]
- so i can use dht in marine tests
- or do custom deployments

**Comment by folex** [comment]
What do you mean by "redistribute"?

Can you please describe how would that help using AquaDHT in marine tests?

Can you please describe what is preventing you from doing "custom deployments" right now?

**Comment by dzmitry-lahoda** [comment]
should i compile actual wasm file from sources and maintain it up to date? I would prefer do download some version of wasm file form somewhere for our builds. and when i got updates to dht aqua, i can get updates to wasm from same source.

i need to produce DHT records and pass these into API of our services. simples way to do that is to load that service into marine tests, save and load values, i do not want to mock DHT or something.

I do not want to maintain up to date fork of DHT and I cannot put DHT as part of subrepo because of easy
```
error: current package believes it's in a workspace when it's not:
current:   /aqua-dht/service/Cargo.toml
workspace: /Cargo.toml
```

**Comment by folex** [comment]
Currently, we're publishing .wasm in releases wrapped in .tar.gz. Here's a link that always points to the latest release:

[https://github.com/fluencelabs/aqua-dht/releases/latest/download/aqua-dht.tar.gz](https://github.com/fluencelabs/aqua-dht/releases/latest/download/aqua-dht.tar.gz)

Would that suffice?

![image](https://user-images.githubusercontent.com/1949356/129882568-9e046f24-02fb-4fd3-85eb-bd4ccbcca674.png)

**Comment by dzmitry-lahoda** [comment]
i see. dht itself uses curl agains sqlite on each build. so it will make support harder and co updated npm aqua and wasm. could wasm be put into npm?
