### ISSUE TITLE
add api to get random value out of key

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua-dht#46]
so can chose any service randomly out of registered

**Comment by dzmitry-lahoda** [comment]
kad provides randomness in form of distance by passing aqua with client generated random parameter https://github.com/fluencelabs/fluence/issues/1180

**Comment by justprosh** [comment]
This functionality will be provided later in Aqua

**Comment by dzmitry-lahoda** [comment]
hi, when?
