### ISSUE TITLE
add ability to get latest value or latest n values

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua-dht#50]
for behavior like online presence it immediately useful

**Comment by justprosh** [comment]
For now, values are sorted by weight but you will be able to sort values as you want later in aqua

**Comment by dzmitry-lahoda** [comment]
nice, so timestamp can be weight. but sorted property by w is nice do document)

**Comment by justprosh** [comment]
Weight is not timestamp, it will be passed from trust graph

**Comment by dzmitry-lahoda** [comment]
oh, nice do document that. so what value should me path when using it from aqua?

**Comment by dzmitry-lahoda** [comment]
so when feature will be here? very usefull for publish service discovery of get me latest?
