### ISSUE TITLE
Add enum for errors

### ISSUE THREAD

**Issue by justprosh** [fluencelabs/aqua-dht#59]
And use in tests instead of duplicated hardcoded strings

**Comment by justprosh** [comment]
It's for internal use and tests only

**Comment by folex** [comment]
The issue isn't clear, maybe add an example or elaborate a little?

**Comment by justprosh** [comment]
I have this as error message: 
```
f!("Requested key {key} does not exist on this peer"))
```
 and should repeat it in tests a lot:
 ```
         assert_eq!(result.error, f!("Requested key {key} does not exist on this peer"));
```
But I can use some custom error with .to_string()
